### ISSUE TITLE
Scanner status bar should be white

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#472]
Since the background is mostly black and the rest of the text and buttons are white. Will need to switch back to black on iPhone for the screens that have a lighter appearance.

**Comment by Smartcop** [comment]
Updated @justinanderson 
The nav bar is white on the iPhone and the status bar is black
On the iPad the nav bar is black and the status bar is black.  

What would you like to do?

**Comment by justinanderson** [comment]
Transparent navbar with white navigation items and a white status bar on both iPhone and iPad. The trick is to keep a normal navbar style on the history screen on iPhone.

**Comment by Smartcop** [comment]
This needs to be tested on a iPad but iPhone looks all good to go on the
4.0/scanner-module-status-bar branch
