### ISSUE TITLE
Libraries research consultation form

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#514]
- Topic field should be a free text field, not a list with the same options as Subject.
- Course should be optional.

**Comment by Smartcop** [comment]
@LoganWright 
@justinanderson 
It is saying invalid topic for me also.  When I go to this link https://mobile-dev.mit.edu/apis/secure/libraries/forms/askUs it has a list of topics that are valid.

**Comment by justinanderson** [comment]
Assigning to myself as this is now dependent on a server-side change. I've verified this works once the server-side change is in place.
