### ISSUE TITLE
iPhone - Tours on production.

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#599]
Tours will not let you get to tours screen if you are on the production server.

![screen shot 2014-12-18 at 6 30 11 pm](https://cloud.githubusercontent.com/assets/1474560/5497831/e7751452-86e3-11e4-929e-e2b306fa0942.png)

**Comment by Smartcop** [comment]
:+1:

**Comment by justinanderson** [comment]
I wouldn't close this. It's good to leave open as a reminder that it's not fixed in production yet.

**Comment by Smartcop** [comment]
@justinanderson Ok dok.  I was just closing because Issue #601 references this issue.

**Comment by justinanderson** [comment]
Assigning to myself since updating production is on my plate.
