### ISSUE TITLE
People Directory - iPhone 6+ - First cell is not aligned with following cells

### ISSUE THREAD

**Issue by transitmark** [MIT-Mobile/MIT-Mobile-for-iOS#719]
![screen shot 2015-01-12 at 4 54 04 pm](https://cloud.githubusercontent.com/assets/1474560/5711846/a200c1cc-9a7b-11e4-993a-d9f61ed83a05.png)

**Comment by Smartcop** [comment]
edit: iPhone 6+

**Comment by Smartcop** [comment]
Note: 
The first cell is set to be 15 away from the left.

Cell separator insets for following devices are:
iPhone 6+ [20]
iPhone 5 [16]
iPad [15]

**Comment by Smartcop** [comment]
Note:
First cell is a UIView and not a UITableViewCell

**Comment by Smartcop** [comment]
I don't know another way to do this.  You have to see the cells left inset before setting the view's left inset.
6885d1f

**Comment by Smartcop** [comment]
Right now the cells are just standard cells.  We could make the cells custom and then change the left constraint ourselves to a number of our choosing.  If we do this we should have a standard value throughout the entire app.
