### ISSUE TITLE
Shuttles map doesn't change number of vehicles while you're looking at it

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#776]
Note this is for 4.0.1.

1. On the route or fullscreen map for the Tech Shuttle at 3pm (one vehicle that time of day).
2. Wait until 4:30 or so for the route to switch to two at a time. You'll see two red dots in the list of predictions indicating two active vehicles, but the map still only shows one vehicle.
3. Go back to Shuttles home and then into the Tech Shuttle again, and now it has two active vehicles.

This happens when transitioning from no active vehicles to some as well. No vehicles are visible on the map.

I'm not sure what happens if there are already vehicles on the map. Hopefully it doesn't leave stale vehicles on the map.

**Comment by rosslebeau** [comment]
@justinanderson I've mocked this up with some local JSON to repeat the vehicles call adding vehicles, and it seems to work fine every time. There is a bit of a delay, but after like 30 seconds the vehicles were all always showing for me.

I'll do some testing with the real web services tomorrow using the Tech Shuttle to see if there are other things in play. Today it seems the shuttles are mostly off.

Was this only on iPhone or did it happen on iPad as well?

**Comment by justinanderson** [comment]
@rosslebeau I've only seen it on an iPhone so far.

**Comment by rosslebeau** [comment]
Ok that's interesting then. I was thinking the error was in the maps code but that is universal. I'll look for some things that would be unique to iPhone.

**Comment by justinanderson** [comment]
@rosslebeau It might happen on iPads too, but I haven't seen it yet.

**Comment by rosslebeau** [comment]
@justinanderson ok, after testing a bunch with mocked data and real data, I am pretty confident in saying that this isn't an issue anymore. I could not reproduce it, but I have an idea of how it may have occurred - we have since changed the code, however. I have tested the current setup as well as fixed the issue I think may have been happening. If you see this again, let me know.
