### ISSUE TITLE
iPhone Dining home choosing wrong house dining venue on tap

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#787]
Tap Baker and get Next. Tap Next and get Simmons. Seems like Baker, Maseeh, etc are sorted by short name for display but didSelectRowAtIndexPath is using the non-sorted order.

**Comment by Smartcop** [comment]
performWebserviceCall is called everytime the view appears.  After the new data is pulled down a new fetch is never completed and we do not sort the new data although it has changed.

We could move performWebserviceCall to viewdidload or just perform [self performFetch]; in 

    [MITDiningWebservices getDiningWithCompletion:^(MITDiningDining *dining, NSError *error) {
[self performFetch];
}];

**Comment by Smartcop** [comment]
Everytime the home dining view controller appears*

**Comment by Smartcop** [comment]
@LoganWright 

I have moved [self performWebserviceCall]; to viewDidLoad and call performFetch in the getDiningWithCompletion completion block and it appears to solve this issue.

- (void)performWebserviceCall
{
    [MITDiningWebservices getDiningWithCompletion:NULL];
    [MITDiningWebservices getDiningWithCompletion:^(MITDiningDining *dining, NSError *error) {
        [self performFetch];
    }];
}

**Comment by justinanderson** [comment]
:+1:

**Comment by justinanderson** [comment]
Still happening after all in the released build of 4.0.

**Comment by justinanderson** [comment]
Moving to 4.0.1 and making it a blocker for that release.

**Comment by Smartcop** [comment]
narrowed down to Reskit not updating core data

MITDiningWebservices
+ (void)getDiningWithCompletion:(MITDiningCompletionBlock)completion
getObjectsForResourceNamed

**Comment by Smartcop** [comment]
edit: the above is issue #816

**Comment by justinanderson** [comment]
Fixing this temporarily by sorting house dining venues server-side.
