### ISSUE TITLE
Dining - iPhone

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#790]
When paging through a dining hall with no meals and stopping on a Friday when today is a Monday rotating the device to landscape sends us back to Monday.

**Comment by Smartcop** [comment]
@LoganWright 

Click on McCormick rotate device and back on Monday Feb 2.  Today is Feb 5.

**Comment by LoganWright** [comment]
@Smartcop  

I found it, it was an issue w/ case sensitive string comparison.  Will be fixed in the next PR.

**Comment by Smartcop** [comment]
:+1: once that PR is merged in

**Comment by Smartcop** [comment]
:+1:
