### ISSUE TITLE
Remove Secrets File

### ISSUE THREAD

**Issue by LoganWright** [MIT-Mobile/MIT-Mobile-for-iOS#795]
@justinanderson @Smartcop 

It was mentioned in our latest meeting, but I just wanted to verify that we want to remove this dependency from the project.  I did a search and the only file using it currently is `MITMobileServerConfiguration.m` and the only keys it's using are:

```ObjC
extern NSString * const MobileAPIServers[];
extern NSUInteger const MITMobileServerConfigurationDefaultIndex;
```

If neither of these is secret, I don't see any reason why we couldn't move them to the server configuration class and remove all secret requirements.

**Comment by justinanderson** [comment]
@LoganWright Yeah, Secret.[hm] don't need to exist anymore. Those variables should probably live inside of the method that uses them.

Also, there's a script phase in the target that you can get rid of once you get rid of the Secret files. It was meant to alert users that their fresh clone was missing the secret file, but it's unnecessary now.
