### ISSUE TITLE
iOS 7 devices not bringing up last visited module?

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#800]
Is it me or is the last visited module not coming up after killing the app and starting the app back up on IOS 7 devices?

**Comment by LoganWright** [comment]
@Smartcop - I don't think it's an issue.  If I run the app, open a module, and then run the app again from Xcode, it kills the app in a way that it can't remember.  (This tends to happen w/ userDefaults, I'm not sure how the module is being remembered).  But, if you kill the app from the simulator, ie: double tap home button and flick up, then re run from Xcode, it seems to work every time.

**Comment by bskinner** [comment]
The module identifier is being saved via NSUserDefaults but I am not calling ```-[NSUserDefaults synchronize]``` so it's entirely possible the app is being killed before the setting is written out to disk.

**Comment by Smartcop** [comment]
:+1:
