### ISSUE TITLE
Remove as many warnings as possible

### ISSUE THREAD

**Issue by rosslebeau** [MIT-Mobile/MIT-Mobile-for-iOS#802]
Starting with preferredMaxLayoutWidth ones

**Comment by rosslebeau** [comment]
@bskinner What's the reason for this property override with `weak` instead of `strong`? Xcode is complaining about it.

https://github.com/MIT-Mobile/MIT-Mobile-for-iOS/blob/master/Modules/Campus%20Map/CMModule.h#L5

**Comment by bskinner** [comment]
@rosslebeau That was an oversight. It was originally weak and was never changed back. It can be made strong with no problems.

**Comment by rosslebeau** [comment]
@bskinner Cool. So I fixed the majority of the warnings in the project, but left ~10 warnings that were all due to completely internal MIT code. There are some manually deprecated methods, and it seems like some unused methods and whatnot.

I figure it will be easier for you to go through these and fix them rather than me have to ask you what the history behind each one is. I'll assign this to you, lmk if there's more you want me to do here.

**Comment by bskinner** [comment]
@rosslebeau Will do! Thank you.
