### ISSUE TITLE
Dining Entities missing assignsDefaultValueForMissingAttributes

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#816]
Let's say a dining hall day has a message saying "Closed for IAP" but we don't get a message in the next dining data download.  The message will stick around and not be cleared.  assignsDefaultValueForMissingAttributes should be used in this case. 

I think the same case can be said for missingassignsNilForMissingRelationships being missing from some of the dining entities too.

**Comment by justinanderson** [comment]
This one is important to fix quickly, since Spring semester is starting and people with old dining data are seeing new hours plus a stale Closed for IAP message.

**Comment by Smartcop** [comment]
![ios simulator screen shot feb 2 2015 3 45 49 pm](https://cloud.githubusercontent.com/assets/1474560/6008844/a8e8633c-aaf2-11e4-987d-fe987ee9c786.png)
