### ISSUE TITLE
Allow thumbing through iPad meal picker

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#831]
In addition to tapping directly on a B L D to select it, a user should be able to touch down anywhere in that area and the drag their finger over each meal to select it. A lot like how the touch-and-hold map callouts work or how the Photos app supports browsing and picking photos by thumbnail grid. Or how the iOS keyboard works. This would make it less frustrating for users to tap on the meal they mean to select if there are a lot of meals fighting for space in the picker.

**Comment by Smartcop** [comment]
:+1:
