### ISSUE TITLE
[News] Runtime unknown class warnings

### ISSUE THREAD

**Issue by bskinner** [MIT-Mobile/MIT-Mobile-for-iOS#843]
At runtime, the News module prints ```Unknown class MultiLineLabel in Interface Builder file```. The MultiLineLabel class was removed in commit deca107299766293db25b1df64c7d1412716ee36.

**Comment by Smartcop** [comment]
Since this class has been removed the cells do not behave correct in landscape mode.

![ios simulator screen shot feb 12 2015 4 20 41 pm](https://cloud.githubusercontent.com/assets/1474560/6177259/20d174b4-b2d3-11e4-8177-d377d1aea89b.png)
