### ISSUE TITLE
back arrow on shuttle stop should go back to list of stops, not list of shuttles.

### ISSUE THREAD

**Issue by rajiv** [MIT-Mobile/MIT-Mobile-for-iOS#847]
on iphone iOS 8.1.3, app version 4.0.1.

1. go to shuttle section.
1. tap any shuttle.
1. tap any stop in the list.
1. tap the back arrow

you should go back to the list of stops for the shuttle, but instead you are back at the list of all shuttles.

**Comment by justinanderson** [comment]
@rajiv Agreed. It's not always a sensible flow the way we have it now.

There are two ways of reaching the stop screen — tap one of the nearby stops or tap the route then tap the stop — but its back button always acts as if you took the shortest path. It'd be better to treat selecting a nearby stop as a shortcut to two levels deep, so it's always two taps on back to get from a single stop to the root Shuttles screen.

**Comment by Smartcop** [comment]
:+1:
