### ISSUE TITLE
Map tableview added space when coming back from detail screen

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#883]
Search for lathe.
Click on map.
Click on pin on the map.
Click on bubble.
Come back from detail screen.
Click on show tableview.
![ios simulator screen shot mar 17 2015 1 32 27 pm](https://cloud.githubusercontent.com/assets/1474560/6693543/11ecae3c-ccaa-11e4-9212-f75fefa49c98.png)

**Comment by Smartcop** [comment]
iOS 8 iPhone 6

**Comment by bskinner** [comment]
The results table is occasionally incorrectly positioned after dismissing the full-screen map when returning from viewing the detail of a resource.

Steps to reproduce:
    * Open MIT Mobile App
    * Activate 'Mobius' module
    * Perform a search which has a non-zero number of results ('lathe' seems to reliably reproduce the bug)
    * Tap on the map to show the full-screen map
    * Click on a pin to show the callout for a resource
    * Click on callout to show the detail for the selected resource
    * Press 'Back' to return to the search results
    * Dismiss the full-screen map

Expected Result: When returning from the detail screen and dismissing the full-screen map, the table view should revert to it's original position

Actual Result: When returning from the detail screen and dismissing the full-screen map, the table view is occasionally significantly offset lower than it's original position.

**Comment by Smartcop** [comment]
:+1:
