### ISSUE TITLE
Shuttles iPhone 6 rotation blank table / navigation bar size

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#896]
When rotating an iPhone 6 in a stop detail view the navigation bar does not extend to have the title / subtitle in the bar and the table becomes blank.

![ios simulator screen shot mar 24 2015 3 57 35 pm](https://cloud.githubusercontent.com/assets/1474560/6811465/811e797c-d23e-11e4-8d65-db42dc70cbf7.png)

**Comment by Smartcop** [comment]
@rosslebeau 
I think you probably have the best idea why this is happening.

**Comment by rosslebeau** [comment]
@Smartcop I literally JUST completed a huge, complete refactor of all this code haha. This issue doesn't exist anymore, check it out after merging #897 :)

**Comment by Smartcop** [comment]
@rosslebeau Ok dok!

**Comment by Smartcop** [comment]
:+1:
