### ISSUE TITLE
Advanced Search - horizontal scrolling filter strip

### ISSUE THREAD

**Issue by mark-novak** [MIT-Mobile/MIT-Mobile-for-iOS#919]
Advanced searches can have filters in addition to freetext: [[a6]](https://cloud.githubusercontent.com/assets/244952/7141136/92a94d4c-e29d-11e4-9528-cca871b7ea04.png) [[a7]](https://cloud.githubusercontent.com/assets/244952/7141137/9778408a-e29d-11e4-9a62-ec2ee759886c.png) [[b5]](https://cloud.githubusercontent.com/assets/244952/7141145/9f6d8110-e29d-11e4-8317-81864ae17da7.png). Active filters should appear in a horizontally scrolling strip that fits below the navigation bar wherever the search field would be visible.

API-wise, the strip should probably work like a dumbed down tableview with a simple delegate protocol:

- numberOfThings
- textForThingAtIndex
- didSelectThingAtIndex

And it should look like this:

![filter strip example - overflowing right](https://cloud.githubusercontent.com/assets/244952/7141117/6af1737e-e29d-11e4-83cb-31c9c6bc8005.png)

![filter strip example - overflowing both](https://cloud.githubusercontent.com/assets/244952/7141271/795bec18-e29e-11e4-8ba8-8bccf3aaeabf.png)

There's a Sketch file and rendered assets in the Mobile Develop dropbox showing metrics, colors, etc.

It should:

- rubber band at the ends like any scroll view
- not loop infinitely
- fade out at its edges (see "Filter Strip Right End Cap" in dropbox)

This should be pretty quick to put together. @bskinner will incorporate it into his overall advanced search work.

Also note the existence of "Filter Strip Disclosure Indicator" in dropbox.

**Comment by Smartcop** [comment]
@rosslebeau 
just making sure you got the email you were assigned to this.

**Comment by rosslebeau** [comment]
@Smartcop yep working on it today. im just branched off the advanced search branch

**Comment by Smartcop** [comment]
@rosslebeau 
Cool Thanks!

**Comment by rosslebeau** [comment]
@Smartcop if you could give me another task for when I complete this, that would help reduce my downtime too

**Comment by rosslebeau** [comment]
@Smartcop @bskinner This is done and implemented with test data on the branch `ross-mobius-strip`

**Comment by bskinner** [comment]
@rosslebeau Thank you. I'll take a look over it and get it merged in

**Comment by justinanderson** [comment]
I can say at least behaviorally it's what I was looking for. If you're looking to do more, highlighting cells on touch down would be good. With the same highlight style as bar button items get.
