### ISSUE TITLE
Make "Shops & Labs" & "Machine Types" cachable

### ISSUE THREAD

**Issue by transitmark** [MIT-Mobile/MIT-Mobile-for-iOS#961]
On first run of the "Shops & Labs" & "Machine Types" views download new content.  After initial download cache this new data and use it.

**Comment by Smartcop** [comment]
This branch needs some more eyes.  
- [ ] There is no order currently when the objects are shown the first time (when downloading from the server) and any subsequent times from core data.
- [ ] Removing objects from core data needs a review.
